# Site settings
title: Youngmin
email: youngmin@fleep.io
description: 이영민
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: fromminn
github_username: eyoungmin

# Build settings
markdown: kramdown
